### ISSUE TITLE
Go through the readme and add your own I was here section in the webpage

### ISSUE THREAD

**Issue by vansh-goel** [vansh-goel/My-Name#1]

**Comment by MarkusEicher** [comment]
Hi @vansh-goel 👋 My name is Markus and I would like to use this opportunity to make my first contribution to open source during this round of Hacktoberfest. Is it ok to go ahead or do you want to assign the issue to me first? Thanks for your answer.

**Comment by vansh-goel** [comment]
> Hi @vansh-goel wave My name is Markus and I would like to use this opportunity to make my first contribution to open source during this round of Hacktoberfest. Is it ok to go ahead or do you want to assign the issue to me first? Thanks for your answer.

Hey Markus! You can go on ahead and add your section of I was here to the Project

**Comment by AditiBendre** [comment]
Hi, i would like to work on this issue. Can i go ahead and my section to the project?

**Comment by MarkusEicher** [comment]
> > Hi @vansh-goel wave My name is Markus and I would like to use this opportunity to make my first contribution to open source during this round of Hacktoberfest. Is it ok to go ahead or do you want to assign the issue to me first? Thanks for your answer.
> 
> Hey Markus! You can go on ahead and add your section of I was here to the Project

Thanks 👍

**Comment by vansh-goel** [comment]
> Hi, i would like to work on this issue. Can i go ahead and my section to the project?

Sure thing! Go ahead!

**Comment by engineerWhoCodes** [comment]
HI, @vansh-goel I will like to contribute to this project.

**Comment by vansh-goel** [comment]
> HI, @vansh-goel I will like to contribute to this project.

Hey we are having a great influx of PRs and I don't want anyone's section to be overwritten because of accepting a PR which started out before theirs was merged, so give me some time, let me coordinate with the current PRs first and I'll let you know as soon as you can contribute.

**Comment by ELIJAHJOHNNY** [comment]
Hello @vansh-goel Please, can I go ahead to make my own contribution to the project?

**Comment by vansh-goel** [comment]
> Hello @vansh-goel Please, can I go ahead to make my own contribution to the project?

Hey we have a few pending PRs rn because I can't merge in right now it will override someone else's work, so please give me some time, as soon as I have instructed others to add their data to the updated branch and merged them all, I'll message here so that you can go on and contribute.

**Comment by MarkusEicher** [comment]
Hi @vansh-goel. Just wanted to let you know that I didn't do my PR yet. I forked the repo to practice the syncing of an upstream and then resolve any conflicts locally before sending mi PR. You don't have to wait for my PR. Just to inform you, ok?

**Comment by neutr0n420** [comment]
> > Hello @vansh-goel Please, can I go ahead to make my own contribution to the project?
> 
> Hey we have a few pending PRs rn because I can't merge in right now it will override someone else's work, so please give me some time, as soon as I have instructed others to add their data to the updated branch and merged them all, I'll message here so that you can go on and contribute.

Hey let me know also I would also like to contribute to this project
