### ISSUE TITLE
I wanna change the search button in the index page by a search icon button for improve the UI

### ISSUE THREAD

**Issue by Fer-Bar** [vansh-goel/My-Name#117]
I wanna change the search button in the index page by a search icon button for improve the UI using bootstrap icons.
https://icons.getbootstrap.com/icons/search/

**Comment by vansh-goel** [comment]
Sounds great, do work on the issue and show me the implementation using screenshot, if all seems well, will merge it asap

**Comment by koushikpaul-06** [comment]
Hi, can you assign this to me?
