### ISSUE TITLE
Footer needs to be fixed

### ISSUE THREAD

**Issue by vansh-goel** [vansh-goel/My-Name#120]
![Screenshot_20221010_142910](https://user-images.githubusercontent.com/62180044/194831176-c8b02df2-a09d-48fc-a288-0a07fc218fc2.png)

Someone can work on fixing this white strip at the bottom of the page

**Comment by SattyamSamania** [comment]
Hey @vansh-goel can you assign this issue to me. Also explain what to do next

**Comment by itsOmSarraf** [comment]
Raised a PR, have corrected the issue :)
