### ISSUE TITLE
Adjust the size of each blocks

### ISSUE THREAD

**Issue by kavania2002** [vansh-goel/My-Name#152]
I think a few blocks of names are uneven in size. I would like to create a basic template, that could be used by all the names that will be added.

I even have one suggestion, I think we can have a tile that uses only 1/3 of the width instead of the whole width. And that would look very beautiful.

**Comment by vansh-goel** [comment]
> I think a few blocks of names are uneven in size. I would like to create a basic template, that could be used by all the names that will be added.
> 
> I even have one suggestion, I think we can have a tile that uses only 1/3 of the width instead of the whole width. And that would look very beautiful.

Sounds good, you can work on it and send in a PR if it all looks good will accept it
