### ISSUE TITLE
NavBar for users to search their name 

### ISSUE THREAD

**Issue by vansh-goel** [vansh-goel/My-Name#44]
We need to create a Navbar at top which would take the user to their section upon searching

**Comment by mritul** [comment]
@vansh-goel  Can I take up this issue ?

**Comment by vansh-goel** [comment]
> @vansh-goel Can I take up this issue ?

Sure thing! You can go on and write the code and if it works perfectly. I'll Merge it right in.

**Comment by mritul** [comment]
Alright I'll get into work then ! Also , it would be great if you merged this issue under hacktoberfest. Thanks in advance !

**Comment by mritul** [comment]
@vansh-goel the ids given to the h1 tags for each person's name is inconsistent (e.g id for one person is "aman" while others have "Divas" which is in title case) in which case navigating to that section through search input is quite challenging as I cannot convert the input to one particular casing. So can I implement the search such that it navigates to sections where ids are given properly i.e title cased (e.g Divas) and hyphen separated title cased (e.g Ishika-Sharma and not ishika-sharma or Ishika-sharma or ishika-Sharma)

**Comment by mritul** [comment]
I've raised a PR wherein I've implemented the search functionality provided that the users who give the id's to the h1 tag of their names in title casing (like John-Doe, Aman, etc). Kindly review it.

**Comment by ELIJAHJOHNNY** [comment]
I think we can implement the search to convert everything to a particular case(I.e either upper or lower case) … so that way, how it’s written in the tags won’t matter

**Comment by mritul** [comment]
But if the id given in the html code is #johndoe for one h1 tag and #Janedoe for another... Will i be converting the search input to lowercase or titlecase?I

**Comment by ELIJAHJOHNNY** [comment]
I guess then the function should just consider if the text written in the search includes the first few alphabet typed… once it’s filtered like that, it should work

**Comment by mritul** [comment]
Got it ! Will work on it and raise a PR

**Comment by vansh-goel** [comment]
Hey guys! I was just checking the feature on the website and I started out checking with the names near the end and it was working well for them, but Its not working for every name for some reason

**Comment by mritul** [comment]
@vansh-goel The implementation I've worked on functions perfectly provided we search the full names (if the person has a surname)

**Comment by mritul** [comment]
So if i search for "markus eicher" it works

**Comment by vansh-goel** [comment]
> @vansh-goel The implementation I've worked on functions perfectly provided we search the full names (if the person has a surname)

Ah understood! Will check it out, I was searching by First names

**Comment by mritul** [comment]
Yeah sure ! 

> > @vansh-goel The implementation I've worked on functions perfectly provided we search the full names (if the person has a surname)
> 
> Ah understood! Will check it out, I was searching by First names

Yeah sure !

**Comment by Mridul2820** [comment]
Hi @vansh-goel I have added a search functionality with the <h1> of each section
Here's the PR
https://github.com/vansh-goel/My-Name/pull/66
