### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by YasirObaibullah99** [vansh-goel/My-Name#71]
Will add top Contributor and project admin in Readme

**Comment by YasirObaibullah99** [comment]
add hacktoberfest tag also

**Comment by vansh-goel** [comment]
Sounds great can you work on that?

**Comment by YasirObaibullah99** [comment]
Yes

**Comment by Sonal-Maurya** [comment]
I want to work on this

**Comment by YasirObaibullah99** [comment]
@Sonal-Maurya But this work has been completed and its already merged

**Comment by vansh-goel** [comment]
> @Sonal-Maurya But this work has been completed and its already merged

Will it automatically add new contributors though? If it won't then I think people can still work on it, right?

**Comment by YasirObaibullah99** [comment]
Ya it will automatically add new contributors with in a day
