### ISSUE TITLE
We can add a visitor counter.

### ISSUE THREAD

**Issue by ShivamPathak99** [vansh-goel/My-Name#73]

**Comment by vansh-goel** [comment]
That is a great Idea if anyone can implement that, please do

**Comment by ShivamPathak99** [comment]
> That is a great Idea if anyone can implement that, please do

Yes I think I can do It, I'll be working on it.

**Comment by Akshay-21** [comment]
Hey Hi @vansh-goel i added visitor counter in this issue kindly see this and i created PR.
