### ISSUE TITLE
docs: hacktoberfest logo and contributing.md

### ISSUE THREAD

**Issue by klaus0512** [vansh-goel/My-Name#83]
- A Hacktoberfest logo must be added to the README.md file to help the visitor to identify the repository for Hacktoberfest
- A CONTRIBUTING.md file should be there to instruct the visitors about how to contribute to this repository.

**Comment by vansh-goel** [comment]
Sounds great! If anyone can do that please do

**Comment by klaus0512** [comment]
Hey @vansh-goel 
I want to work on this issue, do assign me.

**Comment by Akshay-21** [comment]
Hey Hi, @vansh-goel  i worked on this issue and created PR.

**Comment by klaus0512** [comment]
I have updated the README.md and CONTRIBUTING.md file.
@vansh-goel review it and kindly merge it.
