### ISSUE TITLE
Adding logo or maybe Name of the website on the top-left corner

### ISSUE THREAD

**Issue by neutr0n420** [vansh-goel/My-Name#95]
The Navbar look pretty empty can I add the Name of the website/any logo (if available) in the top-left corner and moved that search bar to the right side?
<img width="1439" alt="Screenshot 2022-10-09 at 12 44 26 AM" src="https://user-images.githubusercontent.com/106504872/194723989-3781bb72-61c3-48d1-b7f7-5bcfa0a00a32.png">

**Comment by vansh-goel** [comment]
That sounds great You can work on it and send in a PR

**Comment by vansh-goel** [comment]
And we do not have a logo for the website as of now, I'll put that up as an issue too I guess

**Comment by neutr0n420** [comment]
for sure 🙌🏻

**Comment by Akshay-21** [comment]
Hey Hi @vansh-goel, could you assign me this one also so, after making logo i will add.
Thank You!

**Comment by neutr0n420** [comment]
> And we do not have a logo for the website as of now, I'll put that up as an issue too I guess

Hey I had made something lemme know is it good to go or not?
<img width="444" alt="Screenshot 2022-10-09 at 1 26 15 AM" src="https://user-images.githubusercontent.com/106504872/194725752-06e11814-cb0b-4586-890a-060a3040706c.png">

**Comment by Ezekiel8807** [comment]
hey can you assign it to me, i would love to work on it

**Comment by neutr0n420** [comment]
> > And we do not have a logo for the website as of now, I'll put that up as an issue too I guess
> 
> Hey I had made something lemme know is it good to go or not? <img alt="Screenshot 2022-10-09 at 1 26 15 AM" width="444" src="https://user-images.githubusercontent.com/106504872/194725752-06e11814-cb0b-4586-890a-060a3040706c.png">

The final result's are looking something like this

<img width="1440" alt="Screenshot 2022-10-09 at 1 48 27 AM" src="https://user-images.githubusercontent.com/106504872/194726462-71427ded-f0e6-4c7d-8a52-1a59ae38851c.png">

lemme know which design did you liked

**Comment by vansh-goel** [comment]
> > > And we do not have a logo for the website as of now, I'll put that up as an issue too I guess
> > 
> > 
> > Hey I had made something lemme know is it good to go or not? <img alt="Screenshot 2022-10-09 at 1 26 15 AM" width="444" src="https://user-images.githubusercontent.com/106504872/194725752-06e11814-cb0b-4586-890a-060a3040706c.png">
> 
> The final result's are looking something like this
> 
> <img alt="Screenshot 2022-10-09 at 1 48 27 AM" width="1440" src="https://user-images.githubusercontent.com/106504872/194726462-71427ded-f0e6-4c7d-8a52-1a59ae38851c.png">
> 
> lemme know which design did you liked

Yeah it looks great! You're good to go, please add it to the nav bar and send in a pull request

**Comment by neutr0n420** [comment]
ok ok

**Comment by neutr0n420** [comment]
Hey @vansh-goel  I had opend a pull request #103  can you have a look at it and let me know if I have to do some changes in it?

**Comment by vansh-goel** [comment]
Hey the logo seems to be coming a bit off from the NavBar, can you look into that and fix it?
![Screenshot_20221009_145249](https://user-images.githubusercontent.com/62180044/194748808-c049fa07-475d-42c4-bdb8-eb4c7b5ab70e.png)

**Comment by Sritam28** [comment]
Hey @vansh-goel , could you assign me this task.

**Comment by saavi16** [comment]
Hey @vansh-goel , could you assign me this task.
