### ISSUE TITLE
Make a Logo for the Website

### ISSUE THREAD

**Issue by vansh-goel** [vansh-goel/My-Name#96]

**Comment by Akshay-21** [comment]
Hey Hi @vansh-goel, Can you assign to me i will design this.

**Comment by vansh-goel** [comment]
> Hey Hi @vansh-goel, Can you assign to me i will design this.

Done!

**Comment by Akshay-21** [comment]
> > Hey Hi @vansh-goel, Can you assign to me i will design this.
> 
> Done!

Thanks.

**Comment by Akshay-21** [comment]
could tell me what name do want to put in the logo?

**Comment by vansh-goel** [comment]
> could tell me what name do want to put in the logo?

"My-Name"

**Comment by Akshay-21** [comment]
> > could tell me what name do want to put in the logo?
> 
> "My-Name"

Ok

**Comment by neutr0n420** [comment]
Hey @vansh-goel should I wait until the logo get's ready ?

**Comment by Akshay-21** [comment]
![my-name](https://user-images.githubusercontent.com/32409386/194726120-bc11490e-61e2-4f13-9293-ec07583d9aec.png)

Hey @vansh-goel  could see this?

**Comment by Akshay-21** [comment]
Hey @vansh-goel i selected some more logos with grey color.

![image](https://user-images.githubusercontent.com/32409386/194728529-be1e8593-b3d6-4baf-80e0-70f26ce88f8c.png)

![image](https://user-images.githubusercontent.com/32409386/194728901-4e2aa42d-d3ff-4e88-bca4-edcea584cc87.png)

![image](https://user-images.githubusercontent.com/32409386/194728914-18cedd2c-ae3e-41c3-930e-4d3801b710da.png)

![image](https://user-images.githubusercontent.com/32409386/194728931-af1a3f9a-5d88-4adb-9252-99610afa8f38.png)

![image](https://user-images.githubusercontent.com/32409386/194728992-cc044c1f-7480-49ef-b68a-73df56af9d25.png)

![image](https://user-images.githubusercontent.com/32409386/194729006-e5e0581a-d96c-4e15-9667-6a9b28e8bd86.png)

**Comment by Ezekiel8807** [comment]
I think text logo will be better

**Comment by vansh-goel** [comment]
Hey guys we decided to go with a logo @neutr0n420 made for now, he'll make a PR, you guys can create more designs and if we like any of them better, maybe we can assign you the task to update the logo

**Comment by Akshay-21** [comment]
Hey @vansh-goel could you see these logos with text name only. 
which one will you prefer?

![logo-color](https://user-images.githubusercontent.com/32409386/194780175-a2e0a25a-1ac7-4302-86dc-0ffced7423f0.png)

![Low-Resolution-Logo](https://user-images.githubusercontent.com/32409386/194780196-ba2a833c-4855-4c13-8a0d-0edeecc3e727.png)

![Low-Resolution-Logo1](https://user-images.githubusercontent.com/32409386/194780207-503caa19-bcca-44a1-9466-f08b83b286ab.png)

![logo-color(1)](https://user-images.githubusercontent.com/32409386/194780214-b23d617e-f37a-4783-af8c-785dfccc65cb.png)

![logo-colorad](https://user-images.githubusercontent.com/32409386/194780220-0422a75b-b070-4e2b-9616-aaed8c38cfe9.png)

**Comment by Sritam28** [comment]
Hey @vansh-goel , am really interested to collab with you, can you please assign me this task.

**Comment by saavi16** [comment]
Hey @vansh-goel , am really interested to collab with you, can you please assign me this task.
