### ISSUE TITLE
change nav bar theme.

### ISSUE THREAD

**Issue by Akshay-21** [vansh-goel/My-Name#98]
Need to change nav bar theme in my-name page.

**Comment by Akshay-21** [comment]
Hey Hi @vansh-goel, one issue i found in nav bar so, could you assign me this i will work on it.
Thank You!

**Comment by vansh-goel** [comment]
Sure you can work on it, and once you're done drop in the screenshots here, and if all seems well, I'll merge it

**Comment by Akshay-21** [comment]
Hey Hi @vansh-goel i have changed header nav bar theme matching with footer. Kindly check this.
Thank You!

Header
![image](https://user-images.githubusercontent.com/32409386/194779917-bb1e59c2-581f-43de-ba18-9d3d56197f88.png)

Footer
![image](https://user-images.githubusercontent.com/32409386/194779932-6ce436ee-2d4a-4d52-8312-a0b0af0d8ec7.png)
